rb-app/config/routes.rb
Rails.application.routes.draw do

  get 'accesses' => 'accesses#index',
    as: 'all_accesses'

  get 'accesses/:id' => 'accesses#show',
    as: 'access'

  delete 'accesses/:id' => 'accesses#destroy'
 
  post 'accesses' => 'accesses#create'

  get 'contacts' => 'contacts#index', 
    as: 'all_contacts'

  get 'contacts/:email' => 'contacts#show', 
    :constraints => { :email => /.+@.+\..*/ },
    as: 'contact'

  delete 'contacts/:email' => 'contacts#destroy',
    :constraints => { :email => /.+@.+\..*/ }

  post 'contacts' => 'contacts#create'

  root :to => redirect('/contacts')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rb-app/app/models/access.rb
class Access < ApplicationRecord
  validates :user,
            presence: true

  validates :url,
            presence: true

  validates :date,
            presence: true

end

rb-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rb-app/app/models/contact.rb
class Contact < ApplicationRecord
  validates :user, 
            presence: true,
            uniqueness: true

  validates :email, 
            presence: true,
            uniqueness: true
          
end

rb-app/app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
 
  protect_from_forgery except: :create

  def index
    @accesses = Access.all
  end

  def create
    Access.create(params.require(:access).permit([:user, :url, :date]))
    redirect_to all_accesses_path
  end

  def show
    @access = Access.find(params[:id])
  end

  def destroy
    Access.destroy(params[:id])
    redirect_to (:back)
  end
 
end

rb-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rb-app/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :get_contact, only: [:show, :destroy]
  protect_from_forgery except: :create

  def get_contact
    @contact = Contact.find_by_email(params[:email])
  end

  def index
    @contacts = Contact.all
  end

  def create
    Contact.create(params.require(:contact).permit([:user, :email]))
    redirect_to all_contacts_path
  end

  def show
    @contact_accesses = Access.where(user: @contact.user)
  end

  def destroy
    @contact.destroy
    redirect_to (:back)
  end
end

rb-app/app/helpers/accesses_helper.rb
module AccessesHelper
end

rb-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rb-app/app/helpers/contacts_helper.rb
module ContactsHelper
end

rb-app/app/views/accesses/index.html.erb
<h1>Acessos</h1>
<table>
<% @accesses.all.each do |access| %>
 <tr>
  <td><b>Usuário:</b> <%= access.user %></td>
  <td><b>Url:</b><%= access.url %></td>
  <td><b>Data:</b><%= access.date %></td>
  <td><%= link_to "Excluir", access_path(access.id), method: :delete %></td>
 </tr>
<% end %>
</table>
<% if @accesses.all.size == 0 %>
  <em>Nenhum acesso encontrado!</em>
<% end %>

rb-app/app/views/accesses/show.html.erb
<table>
  <tr>
    <td><b>Usuário:</b> <%= @access.user %></td>
    <td><b>Url:</b> <%= @access.url %></td>
    <td><b>Data de acesso:</b> <%= @access.date %></td>
  </tr>
</table>

rb-app/app/views/contacts/index.html.erb
<h1>Contatos</h1>
<table cellspacing="10">
<% @contacts.all.each do |contact| %>
  <tr>
    <td><%= link_to contact.email, contact_path(contact.email) %></td>
    <td><%= link_to "Excluir", contact_path(contact.email), method: :delete %></td>
  </tr>
<% end %>
</table>
<% if @contacts.all.size == 0 %>
  <em>Nenhum contato encontrado!</em>
<% end %>

rb-app/app/views/contacts/show.html.erb
<table cellspacing="10">
  <tr>
    <td><b>Email:</b> <%= @contact.email %></td>
    <td><b>ID:</b><%= @contact.user %></td>
  </td>
</table>

<h2>Acessos</h2>

<table cellspacing="10">
<% @contact_accesses.all.each do |access| %>
  <tr>
    <% if access.url.split('/').size == 1 %>
        <td><%= link_to "HOME.HTML", access_path(access.id) %></td>
    <% else %>
        <td><%= link_to access.url.split('/').last.upcase, access_path(access.id) %></td>
    <% end %>
        <td><%= link_to "Excluir", access_path(access.id), method: :delete %></td>
  </tr>
<% end %>
</table>
<% if @contact_accesses.all.size == 0 %>
  <em>Nenhum acesso encontrado!</em>
<% end %>

rb-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RbApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>